name: CI

# Controls when the action will run.
# Triggers the workflow on push.
on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Set up Java Environment
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11

            # Build the ballerina project
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      pack
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm

            # Test the ballerina project
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      test
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm

            - name: Alert notifier on failure
              if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data-raw '{
                  "event_type": "notify-ballerinax-connector-build-failure",
                  "client_payload": {
                    "repoName": "module-ballerinax-snowflake.driver",
                    "workflow": "CI"
                  }
                }'
